Proxy settings added for OWASP Benchmark Crawler to help include the remote hosts of AppScan
arunmuthu255/Benchmark pull request #1
Opened 2021-09-22 07:14 UTC by arunmuthu255

2021-09-22 07:32 UTC, aronsky requested changes
Looks good, but please update with the requested changes.

2021-09-22 07:32 UTC, aronsky commented on runCrawler.bat
> +) else (
This does not cover all cases. It's better to verify here that no arguments were passed, and if 1 or 3+ arguments were passed (not supported configurations), show an error message and exit.

2021-09-22 07:32 UTC, aronsky commented on runCrawler.sh
> +else
Same as in the batch file - cover cases where number of arguments is not 2 and not 0.

2021-09-22 07:32 UTC, aronsky commented on src/main/java/org/owasp/benchmark/tools/BenchmarkCrawler.java
> +                    .setSSLSocketFactory(connectionFactory)
This is code duplication. Instead, replace the connection factory variable in the beginning of the function with the following one:

```java
var httpClientBuilder = HttpClients.custom().setSSLSocketFactory(new SSLConnectionSocketFactory(sslContext, allowAllHosts));
```

Now, inside the `if`, you simply call `httpClientBuilder.setProxy(httpHost)`, and outside, you simply return `httpClientBuilder.build()`.

2021-09-22 19:34 UTC, arunmuthu255 commented on runCrawler.bat
> +) else (
Error message added for non-supported cases

2021-09-22 19:35 UTC, arunmuthu255 commented on runCrawler.sh
> +else
Error message added for non-supported cases

2021-09-23 06:42 UTC, aronsky requested changes

2021-09-23 06:42 UTC, aronsky commented on runCrawler.bat
> +	echo Example: runCrawler.bat 192.168.0.1 53452
Please fix the indentation.

2021-09-23 06:42 UTC, aronsky commented on runCrawler.sh
> +elif [ $# -ne 2 ] || [ $# -ne 0 ]; then
```suggestion
elif [ $# -ne 2 ] && [ $# -ne 0 ]; then
```

Though honestly, it'd be better to just make this the case for 0 arguments (`elif [ $# -eq 0 ]; then`), and put the error in the final `else` clause.

2021-09-23 06:42 UTC, aronsky commented on src/main/java/org/owasp/benchmark/tools/BenchmarkCrawler.java
> +            return HttpClientBuilder.setProxy(httpHost);
```suggestion
            HttpClientBuilder.setProxy(httpHost);
```

As it is, this code shouldn't even compile, since the function returns the result of the `.build()` method, and not a builder... Have you verified the code works?

2021-09-23 12:14 UTC, arunmuthu255 commented on runCrawler.bat
> +	echo Example: runCrawler.bat 192.168.0.1 53452
Done

2021-09-23 12:16 UTC, arunmuthu255 commented on runCrawler.sh
> +elif [ $# -ne 2 ] || [ $# -ne 0 ]; then
I have made the required changes

2021-09-23 12:17 UTC, arunmuthu255 commented on src/main/java/org/owasp/benchmark/tools/BenchmarkCrawler.java
> +            return HttpClientBuilder.setProxy(httpHost);
Yes, it works the same way. However I have updated the code and fixed the indentation.

2021-09-23 12:19 UTC, aronsky approved these changes
LGTM

2021-09-23 12:23 UTC, merged